### ISSUE TITLE
Past epoch proposals Filter

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#10]
user located at past epoch page.
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A2521
<img width="821" alt="Снимок экрана 2022-01-27 в 14 08 18" src="https://user-images.githubusercontent.com/94360080/151770004-b5f709f0-d0b6-4116-8246-b0e8fa5cdec1.png">

1. All voted proposals shows
2. AWAITING YOUR VOTE 
3. Your VOTEs

  **2.** AWAITING YOUR VOTE (empty page)
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A2997
![image](https://user-images.githubusercontent.com/94360080/151347916-5a96d0b0-7a6e-4cd9-ae85-3486f0176222.png)

  **3.** Your VOTEs (empty page)
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A3248
![image](https://user-images.githubusercontent.com/94360080/151347985-c6ac7147-699a-4981-a6a9-54f8386ef9b2.png)

**Comment by Roberrtt** [comment]
1) please align the lines
![image](https://user-images.githubusercontent.com/50007056/165062837-c84dacd0-321d-4c00-9ab8-48ca3897795c.png)
2) When we switched to the old epoch tab , remove the current epoch from the list
3) Make empty pages for "awaiting your votes" and "your votes" filters

**Comment by Roberrtt** [comment]
checked
