### ISSUE TITLE
The search line

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#11]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A3496
<img width="549" alt="Снимок экрана 2022-01-27 в 14 34 31" src="https://user-images.githubusercontent.com/94360080/151772464-9a02d732-5e41-49b1-a54b-89ebc0c48063.png">

the search can be:
1. by number
2. by word
3. by epoch number

**1.** https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A3815
<img width="373" alt="Снимок экрана 2022-01-27 в 14 39 35" src="https://user-images.githubusercontent.com/94360080/151772574-833b1a77-d7ee-4463-a09b-f6db8139c77b.png">

**2.** https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A4138
<img width="375" alt="Снимок экрана 2022-01-27 в 14 39 40" src="https://user-images.githubusercontent.com/94360080/151772616-ca92a7e5-e7fb-4d1c-996a-92afc8229112.png">

**3.** https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A4722
<img width="375" alt="Снимок экрана 2022-01-27 в 14 39 46" src="https://user-images.githubusercontent.com/94360080/151772646-48da8306-c8b0-4068-ac75-f088e418b11b.png">

**Comment by VikMaevskaya** [comment]
Search by number and by word will be only in proposal's title

Search by the epoch number - made in sorting by epoch.

**Comment by Roberrtt** [comment]
1) When we click on search
- Your votes jumps to the next line
- The cross overlaps the word "data"
![image](https://user-images.githubusercontent.com/50007056/168591463-0ac434a5-a331-493a-8352-9194520a4aa8.png)
2) Remove words from search "epoch,description,date"
![image](https://user-images.githubusercontent.com/50007056/168608976-ef55c657-3906-49b4-8495-a387f9507372.png)
3) If we enter the title name from a past epoch while in the current one , the search will not find anything
![image](https://user-images.githubusercontent.com/50007056/168593603-495f61c8-b545-40ad-8c0d-67354f4b7e6b.png)

**Comment by Roberrtt** [comment]
checked
