### ISSUE TITLE
Dapp store view / voting

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#12]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=550%3A2216
![image](https://user-images.githubusercontent.com/94360080/151352688-d5bb5df1-b00e-4fb5-a273-98b134437b36.png)

To add Voting Dapp in Dapp store between BeamX Dao and NFT Galery

**Comment by Roberrtt** [comment]
It will be tested on Tightness and Mining

**Comment by Roberrtt** [comment]
checked
