### ISSUE TITLE
The proposal page, no voices / Current epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#14]
When the epoch begins all future proposals transform in present proposals. 
The first person who comes to vote will see voices blank Proposal.

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4886
<img width="693" alt="Снимок экрана 2022-01-27 в 16 06 55" src="https://user-images.githubusercontent.com/94360080/151772847-7e37cd6b-9b11-46a6-ac96-1753c3acee9b.png">

1.  the proposal number
2. the title
3. the publication date (date when proposal was created)
4. the link to the forum discussion
5. YES/No buttons
6. Yes voices progress line
7. Quorum line (separate task)
8. No voices progress line
9. Voting Info:
  9.1 Total staked
  9.2 Voted - total voted for the proposal (=0, if nobody have voted yet)
  9.3. Your staked - user's personal staked for current epoch
  9.4 Quorum + quorum notification (separate task)
10. Proposal description (separate task for Facilitator)

all this steps create when Facilitator create proposal (separate task)
![image](https://user-images.githubusercontent.com/94360080/151366248-a56c0f39-e0fc-46bf-b703-aaceb6f4e8dc.png)

**Comment by AndreyDyakonov** [comment]
In proposal page (current epoch) the "Voted" (9.2) position is missing, and it must be =0, if nobody have voted yet

![2022-04-14_14-49-32](https://user-images.githubusercontent.com/85252690/163386001-c5ce8239-1875-40a3-9c51-9d776d3a95d9.png)

**Comment by Roberrtt** [comment]
If propols has no voices , please remove lines (Votes Yes\No)
![image](https://user-images.githubusercontent.com/50007056/165086728-ac098a8a-8708-40da-8157-8d5d54e1d857.png)

**Comment by Roberrtt** [comment]
checked
