### ISSUE TITLE
The proposal page, user don't voted / Current epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#15]
When the epoch begins all future proposals transform in present proposals.
The user comes to vote and will see how users voted for this proposal before him.
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4415
<img width="669" alt="Снимок экрана 2022-01-27 в 16 40 33" src="https://user-images.githubusercontent.com/94360080/151776010-a86410a5-3213-4f61-9227-8713bd08e8cf.png">

The progress line is painted in a way that is proportional to the number of votes received. the entire length is  - total staked.
1. Yes progress line - shows how many voices has been given for this proposal from the beginning 
of the current epoch
2. No progress line - shows how many voices has been given for this proposal from the beginning 
of the current epoch.
3. sum of No and Yes voices for this proposal
4. If the quantity of Yes voices is less than quorum than red triangle.
5.  the quantity of Yes voices
6.  the quantity of No voices

**Comment by Roberrtt** [comment]
1.Please make the name at 1 height
![image](https://user-images.githubusercontent.com/50007056/163355086-69186e59-ec8c-4097-83a1-09f884c28f83.png)
2,There is no "Voted,, Voted ,Yes Voted No" if wallet didn't vote
![image](https://user-images.githubusercontent.com/50007056/163355989-20bd2b2b-4111-487e-982c-2c5b9414a1ab.png)

**Comment by Roberrtt** [comment]
1) make sure that the amounts are in the area of the green or red line as in the design
![image](https://user-images.githubusercontent.com/50007056/163786976-961b803f-8a5f-4326-ba1b-58b806fc1559.png)
2) make sure that the "BEAMX" is next to the value and not under it, as in the design
![image](https://user-images.githubusercontent.com/50007056/163787103-3ad73ac1-1d1d-4b0d-9dfc-61de2ebcada1.png)
3) values for voting (yes/no) should have the text "beamx" next to it, as in the design
![image](https://user-images.githubusercontent.com/50007056/163787520-ac5dae67-b20b-48aa-82fc-e046b14ed403.png)

**Comment by VikMaevskaya** [comment]
i'll make the separate task for small changes in this area. and task how to display big numbers

> 1. make sure that the amounts are in the area of the green or red line as in the design
>    ![image](https://user-images.githubusercontent.com/50007056/163786976-961b803f-8a5f-4326-ba1b-58b806fc1559.png)
> 2. make sure that the "BEAMX" is next to the value and not under it, as in the design
>    ![image](https://user-images.githubusercontent.com/50007056/163787103-3ad73ac1-1d1d-4b0d-9dfc-61de2ebcada1.png)
> 3. values for voting (yes/no) should have the text "beamx" next to it, as in the design
>    ![image](https://user-images.githubusercontent.com/50007056/163787520-ac5dae67-b20b-48aa-82fc-e046b14ed403.png)

**Comment by iscander01** [comment]
Not relevant according to https://github.com/BeamMW/dao-voting-app/issues/44
