### ISSUE TITLE
The proposal voted Yes / Current epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#16]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162
<img width="698" alt="Снимок экрана 2022-01-28 в 09 54 14" src="https://user-images.githubusercontent.com/94360080/151776735-54cc00f8-a73b-4697-81d2-259de7f439c8.png">

more clear view 
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10413
<img width="142" alt="Снимок экрана 2022-01-28 в 09 56 48" src="https://user-images.githubusercontent.com/94360080/151776756-cac82f3f-be3c-4860-babc-1da26b3d7248.png">

**Comment by Roberrtt** [comment]
1.make propasal number  same as on main screen, for example:  
number proropsal "change beam lgo copy" is  #0073 on main screen
if click on this proropsal ,then number is #73 , must be #0073
![2022-03-28_12-49](https://user-images.githubusercontent.com/50007056/160396125-17b6b12b-b56c-4f7c-b863-4b5428d04304.png)
![2022-03-28_15-19](https://user-images.githubusercontent.com/50007056/160396546-2cec1d71-ceb4-4873-9647-44306af9ed84.png)

2. add  icon next to the link as in  design
![2022-03-28_12-51](https://user-images.githubusercontent.com/50007056/160396102-7ef7573a-e48a-4790-9259-03c5d853f637.png)

**Comment by Roberrtt** [comment]
Please make text + icon  in one line 
![image](https://user-images.githubusercontent.com/50007056/161497474-f5cd9193-9055-4976-8b43-1d37ad230c85.png)

**Comment by Roberrtt** [comment]
checked
