### ISSUE TITLE
The proposal Voted No / Current epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#17]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4660
<img width="860" alt="Снимок экрана 2022-01-28 в 10 04 50" src="https://user-images.githubusercontent.com/94360080/151776894-48441605-cbb0-4278-ac5f-2189c4479c87.png">

1. when user pushed "no" button, then his choice marked at the proposal
2. "changed decision" opportunity appears. (change decision - [separate task](https://github.com/BeamMW/dao-voting-app/issues/18))
<img width="142" alt="Снимок экрана 2022-01-28 в 09 56 48" src="https://user-images.githubusercontent.com/94360080/151776831-8332f84f-caa1-4c20-9cee-457799e31342.png">

more clear view 
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10413

**Comment by Roberrtt** [comment]
checked
