### ISSUE TITLE
Change decision (change vote)

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#18]
when the user changed his mind and decided to change his vote decision, he pushed the "changed decision"
<img width="142" alt="Снимок экрана 2022-01-28 в 09 56 48" src="https://user-images.githubusercontent.com/94360080/151776953-59042087-fa0c-4109-b9aa-ca71f7a7405e.png">

"changed decision" opens a pop-up
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A4152
<img width="199" alt="Снимок экрана 2022-01-28 в 10 10 59" src="https://user-images.githubusercontent.com/94360080/151777006-97ce32ec-1694-43a4-99f7-c47b82a9c5af.png">

where can be 2 messages type:
1. the user voted "no" -> "You voted NO. Are you sure you want to change your current decision in proposal “Proposal Title”?
2. the user voted "yes" -> "You voted YES. Are you sure you want to change your current decision in proposal “Proposal Title”?

After he approve changing he goes to "not voted proposal page". his votes are subtracted from the previous decision.

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4415
<img width="366" alt="Снимок экрана 2022-01-28 в 10 10 45" src="https://user-images.githubusercontent.com/94360080/151777109-8e11112c-adb0-47e5-9759-b0a66bf13a35.png">

**Comment by Roberrtt** [comment]
When we click the "change solution" button, then in the pop-up  we can only "withdraw" coins
![image](https://user-images.githubusercontent.com/50007056/164260533-7eae0333-dddb-4312-80ea-7337a7ad0b45.png)

**Comment by Roberrtt** [comment]
checked
