### ISSUE TITLE
the proposal / Future epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#19]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A2243
<img width="765" alt="Снимок экрана 2022-01-28 в 11 18 55" src="https://user-images.githubusercontent.com/94360080/151777255-f5150a94-d45d-4537-8474-4682680c570c.png">

for the future epoch proposal:
1. no voting buttons
2. no voting progress lines
3. **massage  "The voting will be active when epoch #N comes."** where N - the number of epoch when proposal will be voted

**Comment by AndreyDyakonov** [comment]
Checked
