### ISSUE TITLE
The info block on the main Voting page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#2]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A2003

<img width="734" alt="Снимок экрана 2022-01-27 в 10 04 25" src="https://user-images.githubusercontent.com/94360080/151691906-8bc2409d-f887-4c90-9858-8ee6c2ac71b5.png">

1. Completed Proposals - progress line, shows the percentage of voted proposals in the current epoch;
2. The number of the next epoch and date period.
3. “Show future proposals” - link to the next future epoch. Is active when one proposal is added to the future epoch.  separate task #7

**Comment by AndreyDyakonov** [comment]
Checked

**Comment by Roberrtt** [comment]
1.After  first opening of the wallet on Linux, there is no distance between the "withdraw" and "show my public key" buttons
![2022-03-23_15-08](https://user-images.githubusercontent.com/50007056/159696732-57dc1da9-2abd-4e87-b519-6f56fe5a422c.png)
2.make text " copy and close"  in one line for button "show my public key"
![2022-03-23_15-10](https://user-images.githubusercontent.com/50007056/159696753-1b697d04-d92e-46a8-a046-e0748d357278.png)

**Comment by Roberrtt** [comment]
Please make according to the new design
1. next epoch make the button clickable and shows new proposals.
2. rename "snow future votes" to "show future staking " and show future staking
![photo_2022-03-24_14-44-11](https://user-images.githubusercontent.com/50007056/160362083-89bc005d-7b36-4447-a0ef-00b49fa5d720.jpg)

**Comment by iscander01** [comment]
updated in separate task https://github.com/BeamMW/dao-voting-app/issues/33
