### ISSUE TITLE
Proposal voted Yes/no / past epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#20]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A3918

<img width="538" alt="Снимок экрана 2022-01-28 в 11 27 05" src="https://user-images.githubusercontent.com/94360080/151777476-7e7ff09d-abf4-4a0b-aa70-6f29f48e5f5e.png">

1. user's voting choice
2. for user "The epoch 13 is finished. You can’t change your decision."
3. coloured voting view
4. Voting information for the proposal for that epoch

**Comment by Roberrtt** [comment]
checked
