### ISSUE TITLE
Not voted proposal / Past epoch

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#21]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10183

<img width="621" alt="Снимок экрана 2022-01-28 в 11 50 04" src="https://user-images.githubusercontent.com/94360080/151777535-203ff831-5265-4e6f-95d2-bbf64f882cce.png">

when the user opens past epoch proposal on which he didn't vote:
1. message for user "The epoch 13 is finished. You hadn’t voted."
2. voting information about proposal

**Comment by Roberrtt** [comment]
checked
