### ISSUE TITLE
Quorum

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#22]
**Quorum** -  the minimum number of votes needed to be involved in accepting the proposal. If this minimum is not achieved, the vote will be invalid. The facilitator must establish a quorum. https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A13136
Any integer in the closed interval [0;100] if we use % or any integer number (voices) if we put quorum in BeamX.
Quorum published only for Yes choice. 
can be 3 quorum types:
1. no quorum
2. quorum in BeamX
3. quorum in % from total staked BeamX

**1. no quorum**
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10413
![image](https://lh3.googleusercontent.com/mUxVq-dbxxcMf9UvjsIhGvRPLfZwm63Mut2s--D4Y-Zusy67-GYKbgyKzUrM8tbgtYH9OoWktqh7cwUaLKFKf3hQI_BYWICh_XcHhdFS4DgVYSaWUHPUW2Mb1q3FYQq__zngx0OblSeeng_aZw0qA5je6GbxR3PUdjaAXtvGE8VO4VXw3VaVW07qPXIa1VvqEooN5G380n5m9rW1wv4b58aabfMcRftcBRJVmqL7LCqnIlXnGNz7OhZjd8WJr-BBZ_e8d1XoynGnMdy24A8h2yBYdfjFCeEgy0R-GHPKFrIDwfPQGtmBL3GbhBaOv82e0cx8U-v1ZutP838jIagcGXQATLt34nh4QGHqmuljyGAqwbOtHrxgoDRNYoyiCX1BDk27bXdP4GzSOZ2f3X59h_yitlX2wg2ZR6UImY9CQU0Av_Vz_GnFHXp4Dv4XfkeJO6wEEep_7VYyci7aZytCyIJsJsCV3tPGpolDIQuGxempfY-L1ecl9F9-pYWLu0v7averRhyddUeWjaItdl8I6o5oD1vEvdTBjv1fO8xDz3D3akDSJaqI1m5xk0Y5S6rEfS9K0bKcehw65tCa4iVgnT2OWTCh2exsu-gC0c5ZiZgT8TICSLjUIi2_07TZFIvmI3C6Zi404gAVNPqcN_2X3wUHzIemwN-83LXZ6dn9nenjBCSlBABXm7XP8yX3vhMl118d3lOM7T6uIzG0InNWRWE=w1312-h302-no?authuser=0)

**2. quorum in BeamX**
when the user put cursor on the quorum dot-line the explanation is shown
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162
![image](https://lh3.googleusercontent.com/i-DQOZTrAdUbUgoei6bD59kYpQM5J2j1Omq_OzoS0ZPHMZxg7bUNPOMq7wXHnYHRJFS9L59ler7OzftuG-hS5B5MK5rG09uAdAHMs7pq-tjbgkv7Laqd1vClRq4mKvy7INfXRRYr0ncNSdv5oY0OrQejrD2LMapj72WLREUP66ebwDwLJJUK-6lYNMAGMtvc9w2OXcX18N2vHSehuWdp2-49g8I3drXZVhagy4Sevliszp7X63fkG0hZZeZ9tVTQX1PhGp6Wdpg3vmskRf6M6mKjx696GeB0w7uu6MT03Xfqv_w6x07x-bOttpMz8-QTHNJ8Nj-tMUju3b3aUUc7Mu-hynhwsh6lY7clsLiV3OdfmaB9JWDb9Jb5rVrsT5MCC64B5q4kIwpLnGtscuNV89WtjRHurAXXbb_wPi8S1Te_O-6A8tAmGkyBeiyOpd9Cqa5CdvJ1ivMTmbFZm8KqryZI5527XegSdU-DV_2hOu4rQhTOp_6t8IELGjEXdNUn51W9P9ZJgebj_t4bx-LihgTUTSoZ3YNKwgZzEwZxUX240tuIAj9x_r_Ck0qpoqPKxYPiD52OCssxmUMHLVHu-hNX9Sn0fIiofOhmDJNADm9ifu6C7ObZD0rnj9d-RUVGOGm_wCBUpHsLiAFcqJb3Y0JBHHr9ioEXEN9eUeA6gT2Gc4EtFPYmrYNBIWwMbXaMTEOBh4uPGUq9atzTZXd2NXg=w1226-h234-no?authuser=0)

**3. quorum in % from total staked BeamX**
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4660
![image](https://lh3.googleusercontent.com/zLuBLC1qsKzPY4U8VnGquEA7WEQYacp_oTlM6XW2wuKdsnp129dWKcqrkjJ9EXaM4RU3baTb49L_TysqCGt_FJBxHNKWwO5c6_Dk8WVwFlkTSGMrYmja0kRnGlwupMsNiulFftUpSRgDpugxZo4_DBxIQ0SR0-xQynkPv-i_pB7NJstviRno6X2dJo377IqAJZCibXLW5SoVhYJThzipzVBmlqdnxUVK4QnV7_N_PwNrQLtV3hDBrSpBSLhqQv5dCxE87Hnz3sQhuAs849hhBTlBboNdYXxzl2rwV7i_O8RBYiNgfHU7ysOC3RU60BBjR_wSADDi4omSa-Nd3L-DYBEHUQ8ITc4R9fXQA-vO5OlOhhSvOEUq81QxzqeYh_9FvhSvmXwo8KBrXx87BVd3wweBDnmscE_I_6oA_iSSVS91tandVu4_XI4ASPJAKvnJLH5o_vWrcvn5H9rm8TdMGpUAq2LgLgMZMEAjBrq3IPWatYkkPgkyAIBClAghgdXdgoBi_wBuUobLCI-3oTSrp1GITORu-0b0wX7hDCZXCzHounBALRnQQKCA4pTZ-QRg89deucbsetczutbSS8hZqDwJ3arpHkAQArLqYBLLXUa-Bmz5BMRVG-ZgqlckxbSsfGpdEcFm3GOZvJYm6RssIOBsFhpP7UjQc8apkhWUw7CzO5XGjqx4FJOkTtK9xRPri2ajC5BDzWCjx2RyzhneJ2E=w1234-h230-no?authuser=0)

**Comment by Roberrtt** [comment]
1)The table arrow is located further from the line
![image](https://user-images.githubusercontent.com/50007056/163785565-19330953-2269-4d6f-bb16-065a579ee5a6.png)
2) Make the table opaque
![image](https://user-images.githubusercontent.com/50007056/163785617-a68508e9-e16e-4874-ac48-15cecc538a97.png)

**Comment by iscander01** [comment]
Not relevant according to https://github.com/BeamMW/dao-voting-app/issues/44
