### ISSUE TITLE
Create proposal / Facilitator

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#24]
**Facilitator** (Beam Team Representative): The holder of the key that allows:

Create a proposal by sending a special form
<img width="734" alt="Снимок экрана 2022-01-31 в 14 15 55" src="https://user-images.githubusercontent.com/94360080/151784442-5031df2e-12b4-4765-9f35-49b7eea53e8b.png">

after pushed the button form is opened
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A13136

<img width="560" alt="Снимок экрана 2022-01-31 в 14 18 22" src="https://user-images.githubusercontent.com/94360080/151787123-e88ded13-fc41-466a-bb04-5d006c96c950.png">

The Proposal is published on one page, each block of text in the form is a new paragraph in the Proposal description.
 If the field is not filled in, an empty paragraph does not appear in the description. 

1. Select the number of the epoch in which the Proposal will be published. Obligatory field. Could choose epoch: N+1, N+2, N+3, N+4, where N - is the current epoch;

2. Proposal Title - text, obligatory field, 50 words max;

3. Specification / Proposal Details - text, obligatory field; field must keep the format of the original document (paragraphs, lists, etc. );
4. Quorum - integer number, 
4.1 position %: 3 number max, integer in the closed interval [0;100];
4.2 BeamX position: integer number <= Total value locked BeamX for current epoch. If total value BeamX is withdrawn during the epoch - BeamX quorum position is stable till it <= Total value locked BeamX, then BeamX quorum position decrease at withdrawing quantity BeamX
!!!Any position with “0” or empty field - quorum line doesn’t show.
5. A link to a forum proposal discussion, obligatory field; 
6. Reference link - any kind of links;
7. Total value locked - information for Facilitator, duplicate from the head.
8. Button “Create” - save and publish Proposal, close Proposal form; #25
9. Button “Cancel” - Cancel all changes and close the Proposal form.

**Proposal saved with a publication date in the listed epoch. If the proposal was the first in the epoch, the number of the epoch appears in the filter of the epochs. At the head of the voting page became a visible link “Show future votings”.
Еру sequence number is assigned automatically to the Proposal
**

**Comment by Roberrtt** [comment]
1.There is no way to choose an epoch
2.Make button " + create new proposal" as on the design
![2022-03-17_11-19](https://user-images.githubusercontent.com/50007056/158775551-763f808a-45e1-419d-be4e-a6f45a1151c6.png)
3.Make the "Epoch number" field with "Title" at 1 height ,and text "Epoch number" as in design
![2022-03-17_12-22](https://user-images.githubusercontent.com/50007056/158779237-1d002e10-c638-4bd5-b56d-75d26239b372.png)
4. If we click "cancel" button and open again " Proposal form" ,all changes remained
5.Change the font for the buttons
![2022-03-17_12-30](https://user-images.githubusercontent.com/50007056/158779713-ed9f1dec-e075-4ccb-b1cd-adcacd75d03e.png)
6.Total value locked doesn't duplicate from the head.
![2022-03-17_12-36](https://user-images.githubusercontent.com/50007056/158780845-ca2e82e2-4d0b-4703-9a76-ec7352e3189c.png)

**Comment by iscander01** [comment]
1. in the current version of contract, it is possible to add a proposal only for n+1 epoch

**Comment by Roberrtt** [comment]
3  - It's not fixed
![2022-03-23_16-46](https://user-images.githubusercontent.com/50007056/159718243-75bb89e5-2c6d-4c60-a800-500805452bdf.png)

Change rule for "reference link" ,this isn't obligatory field

**Comment by Roberrtt** [comment]
Please remove this symbol '*" from Refernce lonk
![2022-03-24_11-42](https://user-images.githubusercontent.com/50007056/159877904-4dbcfe17-cafb-472d-b84a-75bbe8a4cd96.png)

**Comment by Roberrtt** [comment]
checked

**Comment by Roberrtt** [comment]
Please correct these fields (% of TVL and Total value locked)
![image](https://user-images.githubusercontent.com/50007056/161498735-96669de7-0f3b-4242-9556-92ceb0ed524d.png)
