### ISSUE TITLE
Go to Home page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#28]
No meter where user located, if he will click on the "Voting" or Voting icon at side menu he goes to the Home page
<img width="391" alt="Снимок экрана 2022-02-01 в 12 18 18" src="https://user-images.githubusercontent.com/94360080/151942075-7c41155b-7db8-4fc7-89f4-b580e7b6d5a2.png">

<img width="182" alt="Снимок экрана 2022-02-01 в 12 18 23" src="https://user-images.githubusercontent.com/94360080/151942088-da39c4a2-52d6-4b19-9771-d74d945de62b.png">

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818
<img width="665" alt="Снимок экрана 2022-02-01 в 12 19 13" src="https://user-images.githubusercontent.com/94360080/151942157-276c43f6-f619-4c91-8787-f3b7c02ef14e.png">

**Comment by Roberrtt** [comment]
1.Voting icon at side menu he doesn't go to the Home page
2. Remove "BeamX Dao Votins" leave only Voting
![2022-03-17_12-51](https://user-images.githubusercontent.com/50007056/158783862-d258f675-e13e-4d8c-bbbb-467ac248ec56.png)

**Comment by iscander01** [comment]
"BeamX Dao Voting" and voting icon are elements of the desktop client and cannot be changed from dapp.
