### ISSUE TITLE
Deposit and Withdraw (Voting)

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#3]
Deposit
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A6331
<img width="449" alt="Снимок экрана 2022-01-27 в 10 09 24" src="https://user-images.githubusercontent.com/94360080/151691984-b2532408-7354-4e11-a1fb-2dc0d4a551ef.png">

Voting deposit confirmation. **except for the red block**
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A6743
<img width="435" alt="Снимок экрана 2022-01-27 в 10 09 32" src="https://user-images.githubusercontent.com/94360080/151828218-a8851fe8-fbea-4340-b1c5-3226e1ee6a7b.png">

Voting deposit notifications. 
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A7181
<img width="408" alt="Снимок экрана 2022-01-27 в 10 09 40" src="https://user-images.githubusercontent.com/94360080/151692007-e3dd96bb-5763-4cdb-aed8-70191c719bd7.png">

Withdraw
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A9493
<img width="317" alt="Снимок экрана 2022-01-27 в 10 09 51" src="https://user-images.githubusercontent.com/94360080/151692014-1b8723af-669e-4efe-8266-e1b5d600b187.png">

Voting Withdraw confirmation **except for the red block**
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A9756
<img width="314" alt="Снимок экрана 2022-01-27 в 10 09 57" src="https://user-images.githubusercontent.com/94360080/151828823-93faaa1e-a7ff-4d73-82dd-393241216a00.png">

Voting Withdraw notification
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A9255

<img width="294" alt="Снимок экрана 2022-01-27 в 10 10 06" src="https://user-images.githubusercontent.com/94360080/151692028-83d09f2d-701e-44b9-8185-3c57c692a8cc.png">

**Comment by AndreyDyakonov** [comment]
1. Deposit 
1.1 Please add assets name in amount field

![2022-03-17_13-28-32](https://user-images.githubusercontent.com/85252690/158792126-c744e26f-ca4c-438a-b760-13898ccc8d46.png)

1.2 Please remove comment in confirmation screen 

![2022-03-17_13-01-05](https://user-images.githubusercontent.com/85252690/158809791-e371e32f-9de6-417d-bd66-4b56605161fc.png)

1.3 Please rename (change) head of confirmation as  in the design 

![2022-03-17_13-29-19](https://user-images.githubusercontent.com/85252690/158809880-7580e504-7d49-4f9a-9b61-673f56a4394e.png)

2. Withdraw
2.1  Please add assets name in amount field
       Align the "max" button to the right edge and widen the sum fields accordingly
       Make the size of the buttons "cancel" and "withdraw" as in the design
       
![2022-03-17_13-29-52](https://user-images.githubusercontent.com/85252690/158810244-e4b3b37b-e7da-4112-aef0-497b70600452.png)

2.2 Please remove comment in confirmation screen 

![2022-03-17_13-06-42](https://user-images.githubusercontent.com/85252690/158811193-5acb3554-c488-4b4c-841c-95407f766778.png)

2.3 Please rename (change) head of confirmation as  in the design 

![2022-03-17_13-07-57](https://user-images.githubusercontent.com/85252690/158811279-2d215f73-7623-4745-a079-bbaae3885cea.png)

**Comment by AndreyDyakonov** [comment]
Checked
