### ISSUE TITLE
Windows for deposit/withdraw buttons 

### ISSUE THREAD

**Issue by Roberrtt** [BeamMW/dao-voting-app#32]
1. When we entered the amount and then reopened the window , the amount left entered should be 0
https://user-images.githubusercontent.com/50007056/160416209-d1c3413f-2521-417f-aae8-6bd2cab3e563.mp4
2. Change color for number 0 when we open window deposit to red if withdraw then to blue 
![2022-03-28_16-44](https://user-images.githubusercontent.com/50007056/160415813-8b3e2386-abf3-431c-b92c-c01f1781ec9e.png)
3.Change the month to English
![2022-03-28_16-58](https://user-images.githubusercontent.com/50007056/160416132-c8e02e26-4d88-498c-9571-26502b676ce0.png)
4. Limit the input after the dot for 8 numbers
![2022-03-28_17-09](https://user-images.githubusercontent.com/50007056/160416601-35e0802e-bae2-440e-b8c8-eb7fa67147da.png)
5.Change fee from 0.0011 to 0.011
6.Make text in withdraw button to be in one line
![2022-03-28_17-12](https://user-images.githubusercontent.com/50007056/160417452-8edfda5d-4d6a-4c6e-bd41-df91b5b1bbb8.png)
7. Make text in one line for deposit/ withdraw windows
![2022-03-28_17-26](https://user-images.githubusercontent.com/50007056/160420381-0c266ce5-89bd-43b7-8714-03f4dd8b50d5.png)

**Comment by AndreyDyakonov** [comment]
1 - not fixed 
If we entered the amount into the "deposit/withdraw"  and then clicked "cancel" and returned to the "deposit/withdraw" window again, the amount is saved

https://user-images.githubusercontent.com/85252690/161529523-cbb17b7a-585b-41ba-8578-6214e9c8a18a.mp4

**Comment by AndreyDyakonov** [comment]
1. Please make the color of error message and the alignment of this message as in BEAM DAO 

![1](https://user-images.githubusercontent.com/85252690/163800408-89c12428-c137-4162-8b76-42c39cd047ee.png)

2.  Please make the incorrect input amount bold the same as if the input amount is correct
     Please add dot after BEAMX
  
![3](https://user-images.githubusercontent.com/85252690/163801023-505fcaeb-6ecb-4f1e-8010-c5b248a6178a.png)

**Comment by AndreyDyakonov** [comment]
Please make the error message alignment by the first character entered

![14](https://user-images.githubusercontent.com/85252690/164198732-2209a737-94b8-4369-b813-85210c40b252.png)

**Comment by AndreyDyakonov** [comment]
Checked
