### ISSUE TITLE
Main page / Changes

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#33]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=1290%3A2472
<img width="654" alt="Снимок экрана 2022-03-30 в 13 29 00" src="https://user-images.githubusercontent.com/94360080/160813405-4f54c36d-a907-4afa-9e85-782fc5feab05.png">

small misspelling in design, words "proposals" and "staked"

Show staked info - separate task

**Comment by AndreyDyakonov** [comment]
1. Please make right alignment for "Show my public key" same as for "Show stakes info" and "Show future proposals" 

![2022-04-06_11-57-591](https://user-images.githubusercontent.com/85252690/161941178-314fb5f9-c4ff-4b96-b077-ca6898efb0b6.png)

2. Please make size of text for "Show my public key" same as for "Show stakes info" and "Show future proposals", its size is smaller

![2022-04-06_11-57-5933](https://user-images.githubusercontent.com/85252690/161941809-4af87d26-decb-444d-8017-3152e12c3d10.png)

3. Please return the previous version of the button "create new proposal"

![2022-04-05_15-03-594444](https://user-images.githubusercontent.com/85252690/161945336-fe4196dc-3648-4f7e-8955-508bc83ec723.png)
