### ISSUE TITLE
changes Facilitator main page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#35]
changes on Facilitator main page:
1. "Create new proposal" put before "Show my public key"
2. "Show staking info" change to "Show staked info"

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10652
<img width="700" alt="Снимок экрана 2022-04-01 в 13 30 55" src="https://user-images.githubusercontent.com/94360080/161246645-1a2de35c-d85e-4aab-b3d5-9a538b1f2674.png">

**Comment by dariatarakanova** [comment]
1. done https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10652
<img width="875" alt="image" src="https://user-images.githubusercontent.com/47353570/161976820-0493ffcf-6c33-478c-8faa-5ec2d8d62691.png">

2. done https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A10652
<img width="773" alt="image" src="https://user-images.githubusercontent.com/47353570/161976736-7f643121-fb93-45f3-b661-05e7ccda7853.png">
