### ISSUE TITLE
Changes at Facilitator page

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#39]
please change **"% of TLV"** at **"% of total supply"** for all pages
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A13136
<img width="684" alt="Снимок экрана 2022-04-14 в 14 19 01" src="https://user-images.githubusercontent.com/94360080/163380755-b4e6fbf9-73f2-4d81-a599-fd49c2538a5e.png">

**Comment by dariatarakanova** [comment]
@VikMaevskaya 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/47353570/163402844-0dd2657f-eca2-4b30-9b38-ca7b4a8e7eed.png">
