### ISSUE TITLE
Menu and Filters (Voting)

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#4]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818
<img width="809" alt="Снимок экрана 2022-01-27 в 10 23 46" src="https://user-images.githubusercontent.com/94360080/151692069-49bb3e3d-d5de-4b15-9963-39bb992718a6.png">

1. Proposals - just word.
2. All, AWAITING YOUR VOTE, Your VOTEs:
All - the list of all proposals
AWAITING YOUR VOTE - the list of the proposals which user doesn't vote yet;
Your VOTEs - the list of the proposals which user have already voted;
3. Search string; [separate task](https://github.com/BeamMW/dao-voting-app/issues/11)
4. Epoch droplist filter;
 the list of epochs. always in position - current epoch, if user didn't choose other one.
The number of future epoch appears in the drop list when even one proposal from this future epoch created.
 
<img width="127" alt="Снимок экрана 2022-01-27 в 10 22 55" src="https://user-images.githubusercontent.com/94360080/151692079-8c16a35b-c743-42b3-9cac-ca0138bce6b1.png">

**Comment by Roberrtt** [comment]
1) The filter does not have the number of the current epoch
![image](https://user-images.githubusercontent.com/50007056/167596236-403484ab-da4d-4364-9356-e408ebaed7e9.png)
2) The filter does not have a future epoch number if one propols is created in the future epoch.

**Comment by AndreyDyakonov** [comment]
If we select future epoch in "Epoch droplist filter" then we can't select other epoch in "Epoch droplist filter"  how can this be done if the current or olds epochs are selected

https://user-images.githubusercontent.com/85252690/168984899-6a6a094c-e27f-416d-85c4-f237ff8b9028.mp4

for example:
1. current epoch
<img width="650" src="https://user-images.githubusercontent.com/85252690/168985136-b23f4036-627a-4f64-bc69-59aea6a4a90c.png">

2. future epoch 
<img width="650" src="https://user-images.githubusercontent.com/85252690/168985186-a5da0199-0ebf-48f2-a5e7-41deb4e45328.png">

**Comment by AndreyDyakonov** [comment]
Checked
