### ISSUE TITLE
Change two words at the "Create proposal" Form

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#41]
please make a few changes:
Voting title -> Proposal title
Voting description -> Proposal description

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=507%3A13136
<img width="478" alt="Снимок экрана 2022-04-15 в 10 28 34" src="https://user-images.githubusercontent.com/94360080/163539684-a1105881-b6b5-404f-b5a4-8b8401142fc5.png">

**Comment by Roberrtt** [comment]
checked
