### ISSUE TITLE
Changes for all proposal's pages 

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#43]
we need to make some changes.
1. Delete quorum line everywhere and all info blocks.
2. Need to show how we will display numbers in millions (e.g. 3.48M BeamX) and thousands (304.42K BeamX). 
<img width="545" alt="Снимок экрана 2022-04-18 в 13 33 15" src="https://user-images.githubusercontent.com/94360080/163796571-9d3811d3-83fd-43a7-b2e7-869a33541bb4.png">
3. Voted yes/no. Marked as Voting results and shown in %

4. Quorum everywhere shows in BeamX. (thousand or millions)

5. at the progress line show another version in thousands and millions

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162
<img width="759" alt="Снимок экрана 2022-04-18 в 12 45 17" src="https://user-images.githubusercontent.com/94360080/163795919-acbf4d99-01e0-44d6-afb2-f4c9eaa800e3.png">

**Comment by dariatarakanova** [comment]
@VikMaevskaya  please check this screen https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162

**Comment by VikMaevskaya** [comment]
> @VikMaevskaya please check this screen https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162

checked. please change the others screens. except  create proposal form
add sometimes numbers цшер 2 symbols after dot.

**Comment by dariatarakanova** [comment]
done

**Comment by VikMaevskaya** [comment]
please turn back Total value locked. without any short cut
<img width="489" alt="Снимок экрана 2022-04-18 в 18 40 08" src="https://user-images.githubusercontent.com/94360080/163833531-d192158e-11ab-49ed-b994-eac4903a2731.png">
