### ISSUE TITLE
Displaying long numbers

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#44]
all numbers over 1010 will be cut.
for numbers from 1010 to 199 994 -> 1.01K to 199.99K
for numbers 199 995 to 999 994 000 -> 1M to 999.99M

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4162
<img width="902" alt="Снимок экрана 2022-04-18 в 17 55 25" src="https://user-images.githubusercontent.com/94360080/163834072-63d61955-e7e9-469e-b6fd-5b6f31ee5bdb.png">

Voting results
Votes Yes/No shows in %. Count as VotedYes/Voted *100%
<img width="155" alt="Снимок экрана 2022-04-18 в 19 45 18" src="https://user-images.githubusercontent.com/94360080/163842015-7125ccd4-f73c-4251-9813-dc9c378e9c85.png">

Total value locked at the New proposal's page stays without changes
<img width="138" alt="Снимок экрана 2022-04-18 в 19 51 26" src="https://user-images.githubusercontent.com/94360080/163842850-133bbb73-cb48-4674-b171-5be0bd8caf0f.png">

Delete quorum line and any quorum info from all of the pages
<img width="392" alt="Снимок экрана 2022-04-18 в 12 45 17" src="https://user-images.githubusercontent.com/94360080/163843219-6f7a7e7a-ad26-4e55-b8f8-a1b714d32c26.png">

**Comment by Roberrtt** [comment]
checked
