### ISSUE TITLE
Create file where will be summarise all  info about using graphical instruments

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#45]
Voting https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A5063

1. colors:
Buttons (deposit, withdraw, etc)
Progress line
Thumb up, thumb down
2. Text ( title, subtitle, other colors, texts)
The head of the page, the main part, proposals card, etc
3. Icons. Marked all icons (backside menu, currency), icons size
4. deposit/withdraw pop-up standard. Colors, text with examples. 
5. Notifications proposal past/ failed https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A5063

6. any other useful info

**Comment by dariatarakanova** [comment]
@VikMaevskaya  
Started working here https://www.figma.com/file/wURoaL1Rifj5tGKaoHSeiN/BEAM-Design-System?node-id=0%3A1
