### ISSUE TITLE
Quorum info pop-up

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#48]
When we set quorum in %, % takes from total supply (100 M)
When quorum doesn't achieve shows red triangle and we need notification:

Need to vote Yes
85M BEAMX
![photo_2022-05-11_16-17-48](https://user-images.githubusercontent.com/94360080/167859287-89e3fbb4-66c0-4d14-96a8-44a78bea07f0.jpg)

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4415
<img width="602" alt="Снимок экрана 2022-05-11 в 16 17 28" src="https://user-images.githubusercontent.com/94360080/167859450-e6ff725e-4eab-40a2-8c35-feb0d8bd2765.png">

**Comment by dariatarakanova** [comment]
Design: https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A4415

**Comment by AndreyDyakonov** [comment]
When the quorum is not reached in proposals in current epoch, the red triangle with the notification is not displayed

https://user-images.githubusercontent.com/85252690/169020069-89854362-9d7b-4b8d-9a36-05346f51bb36.mp4

**Comment by AndreyDyakonov** [comment]
Checked
