### ISSUE TITLE
The list of the proposals

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#5]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818
<img width="710" alt="Снимок экрана 2022-01-27 в 10 28 21" src="https://user-images.githubusercontent.com/94360080/151691854-cc29bfd6-38d3-463e-afdf-931f86f75520.png">

The list of the proposal cards.
At the beginning of the epoch, The proposals are numbered. When the user votes for any Proposal, this Proposal is dropped below ‘not voted’ Proposals.

Proposal card on the main page:
1. The number of proposals;
2. The title of the proposal (Title, Bold);
3. Pending vote - the status of the proposal if user doesn't vote
When user has voted for the proposal:
3. The number of votes in beamX for the current proposal from all users. (voted Yes, voted No)
4. An Icon user’s voting status for the proposal (thumbs up - voted yes, thumbs down - voted no);

**Comment by AndreyDyakonov** [comment]
1. The title of the proposal is not bold 
2. The icon is not displayed in the proposal for which the vote was given (thumbs up - voted "yes", thumbs down - voted "no")
3. The icon is not displayed in the proposal for which the vote was not given (Pending vote)
4. Not displayed the number of votes in beamX for the current proposal from all users (voted Yes, voted No)
5. The proposal for which the vote was given does not move down

![2022-03-18_09-11-50](https://user-images.githubusercontent.com/85252690/158962296-88edd4f9-a448-40d1-acc1-30b93d104147.png)

**Comment by iscander01** [comment]
№5 moved to https://github.com/BeamMW/dao-voting-app/issues/29

**Comment by AndreyDyakonov** [comment]
Please make the button "pending vote" as in design

![2022-03-24_13-38-39](https://user-images.githubusercontent.com/85252690/159904874-98316bfc-e663-4ba0-b227-04218704f5fb.png)

**Comment by AndreyDyakonov** [comment]
If we have a proposal whose description takes up more than one line - button "pending vote" displayed incorrectly

in desktop (window size) 
![2022-03-28_15-53-37](https://user-images.githubusercontent.com/85252690/160406964-76d69a64-0bbc-49e3-8fa9-b92eb963ac5d.png)

in web and desktop (full size) 
![2022-03-28_15-53-55](https://user-images.githubusercontent.com/85252690/160407052-37d98910-1dff-4185-bccd-3371614a2162.png)

**Comment by AndreyDyakonov** [comment]
Checked
