### ISSUE TITLE
Transactions (the bottom of the page)

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#6]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818
<img width="718" alt="Снимок экрана 2022-01-27 в 10 33 44" src="https://user-images.githubusercontent.com/94360080/151692100-5c28652d-792f-4fc8-b6ea-62069c318a0b.png">

At the bottom of the page located the standard block Transactions like in present version

**Comment by Roberrtt** [comment]
It will be checked on Testnet  and Mainnet
