### ISSUE TITLE
The future proposals list

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#7]
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A1917
<img width="593" alt="Снимок экрана 2022-01-31 в 12 24 06" src="https://user-images.githubusercontent.com/94360080/151768949-5549b25a-298b-47d4-9bc1-516ab0edb932.png">

When a user clicks at "shows future proposals" he gets on the future proposals list of the N+1 epoch, where N - current epoch.
It's just a list of proposals without any marks and any possibility to vote.

The main differences from the main page:
1. 'Back' button - goes back on the main page;
2. Menu and Filters line:
 2.1. Future proposals
 2.2. Search line
 2.3. Epoch filter shows N+1 epoch.
 2.4 Proposal card: the number of the proposal, Title

**Comment by Roberrtt** [comment]
Button "Show future votings" doesn't work , it show black screen

**Comment by AndreyDyakonov** [comment]
Checked
