### ISSUE TITLE
The past epoch proposals list/ " show old epochs" button

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#8]
It's several ways to get to past eposchs proposal list:
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=442%3A1818
<img width="800" alt="Снимок экрана 2022-01-27 в 13 51 10" src="https://user-images.githubusercontent.com/94360080/151692166-fd3083b6-ec84-467c-a72f-26aae17719e8.png">

to push the button at the bottom on the main page " show old epochs"
https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=475%3A2882

 
<img width="663" alt="Снимок экрана 2022-01-27 в 13 35 14" src="https://user-images.githubusercontent.com/94360080/151692245-76c39235-d88c-4454-9ca2-d3a9ff688acf.png">

The list looks like the list on the present epoch, two adds:
1. The total voting result
1.1. Green - Proposal successfully passed
1.2. Red - Proposal failed

2. If user didn't voted for the proposal - "The epoch 13 is finished. You hadn’t voted".

**Comment by Roberrtt** [comment]
1.When the epoch is ended, the data is displayed incorrectly (shows that the user did not vote, but he voted).
![image](https://user-images.githubusercontent.com/50007056/166913546-d21e5e7f-8bfb-4587-b07b-a8828a57c95d.png)
2.Sometimes the result does not match on 2 wallets, in 1 it ended in 2 it failed
![2022-05-05_11-05](https://user-images.githubusercontent.com/50007056/166913820-ad91d572-192e-4414-9b12-029902516b40.png)

**Comment by iscander01** [comment]
2. done

**Comment by Roberrtt** [comment]
checked
