### ISSUE TITLE
The past epoch proposal list/ choose epoch in the filter

### ISSUE THREAD

**Issue by VikMaevskaya** [BeamMW/dao-voting-app#9]
User chooses past epoch in the filter:
<img width="127" alt="Снимок экрана 2022-01-27 в 10 22 55" src="https://user-images.githubusercontent.com/94360080/151769155-9115f340-0387-479b-a22a-4a3d4a03f7e7.png">

https://www.figma.com/file/JJwEqNgraxVz0ernKj6ps3/voting?node-id=565%3A2521
<img width="504" alt="Снимок экрана 2022-01-27 в 14 01 55" src="https://user-images.githubusercontent.com/94360080/151769297-9a92b9f8-e6a6-401f-84b0-7fc76ff2ada1.png">

the list past epoch proposals. 
<img width="663" alt="Снимок экрана 2022-01-27 в 13 35 14" src="https://user-images.githubusercontent.com/94360080/151769402-819bba96-8364-4448-b84c-89d067b8650e.png">
 
The list looks like the list on the present epoch, two adds:
1. The total voting result
1.1. Green - Proposal successfully passed
1.2. Red - Proposal failed

2. If user didn't voted for the proposal - "The epoch 13 is finished. You hadn’t voted".

Proposal's filter is in he BeamMW/dao-voting-app#10

**Comment by Roberrtt** [comment]
checked

**Comment by Roberrtt** [comment]
Please align the columns (Vote Yes\No)
![image](https://user-images.githubusercontent.com/50007056/167602535-4d9323c9-d10d-4d8f-aa71-22c08c474eef.png)

**Comment by Roberrtt** [comment]
checked
